import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./component/Providers";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import ToastProvider from "./component/ToastProvider";
import ChatUi from "./component/ChatUi";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ToastProvider/>
          <Navbar />
          {children}
          <ChatUi/>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
